version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgres
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - redis:/data
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]

volumes:
  postgres: {}
  redis: {}
